### PR TITLE
Drop more Controller annotations

### PR DESCRIPTION
**Pull request by jtojnar**
https://github.com/apitte/core/commit/d0e38d9f0242f28a51ffe3c282b8b7f7b3c4411e

### CODE REVIEW

**Comment by mabar** [comment]
There is a composer.lock file which is used to ensure correct versions of libraries are installed. Everyone who will download playground and run `composer install` as described in docs will get broken build.

**Comment by jtojnar** [comment]
Hmm, you are right. Should we pin the apitte/core dependency to a working commit then? Or just rely on people not running `composer update`?

**Comment by jtojnar** [comment]
For now, I have updated the lock files to apitte/core@d0e38d9.

Comparing the changes

* https://github.com/apitte/core/compare/1092fc88f33900681ac9e033187161e50786bac7...d0e38d9f0242f28a51ffe3c282b8b7f7b3c4411e for `apitte/*`
* https://github.com/apitte/core/compare/1616f9a3e2521ce6d6f725a2c5b9fbb988605b24...d0e38d9f0242f28a51ffe3c282b8b7f7b3c4411e for `nette/simple`

the only other breaking change seems to be https://github.com/apitte/core/commit/1263376a5eb72af40e43be6ab0a248f4f9352d0a and all controllers already seem to implement `IController`.

**Comment by mabar** [comment]
Could you commit these lock files?

IController interface was already required by DI, but not really required by other layers. I removed posibility to not have that interface to simplify code.

**Comment by mabar** [comment]
We will release stable version soon, so that `composer update` problem will dissapear.

**Comment by jtojnar** [comment]
Sorry, was pushing to a different repo and did not notice. Pushed here now.

**Comment by mabar** [comment]
Thanks

**Comment by jtojnar** [comment]
Also note that before the release, the playground still needs to be updated to in line with https://github.com/apitte/core/commit/d3c4ceb23ca8cc490d28027d6b34fc3c3dda2b53

**Pull request merged**
