### PR TITLE
Fix: failed opening required 'index.php' in Unknown on line 0

### PR DESCRIPTION
**Pull request by Vlczech**
> php -S 0.0.0.0:8000 -t www index.php
[Mon Apr 16 19:54:08 2018] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Mon Apr 16 19:54:08 2018] PHP Fatal error:  Unknown: Failed opening required 'index.php' (include_path='.;C:\php\pear') in Unknown on line 0

### CODE REVIEW

**Comment by f3l1x** [comment]
Hi, thank you for PR.

I think that correct form is `php -S 0.0.0.0:8000 -t www www/index.php`. You need to setup the `www/index.php` allow to match `api/v1/users.json` url. Please test it.

**Comment by Vlczech** [comment]
@f3l1x : Are you sure? '''php --help''' shows:
'''
php [options] -S <addr>:<port> [-t docroot]
'''
nothing like index.php or anything other is present here..

**Comment by f3l1x** [comment]
Well, I hope so.

http://php.net/manual/en/features.commandline.webserver.php#example-411 

:-)

**Comment by f3l1x** [comment]
Ping @Vlczech

**Comment by Vlczech** [comment]
@f3l1x : Sorry, I probably overlooked.

Original was: `php -S 0.0.0.0:8000 -t www index.php` (**without www/** before index.php), which does not work.

`php -S 0.0.0.0:8000 -t www www/index.php` also works good, but if php is configured, that main script is index.php, this is quite equivalent as I fixed in PR.

**Comment by f3l1x** [comment]
Well, its not. www/index.php is here as router, so all endpoints goes here. It’s works like .htaccess, but without Apache.

**Comment by Vlczech** [comment]
I'm sorry, it was very quick conclusion, but I have a great suspicion of some disturbance.

I told that `[..] -t www www/index.php` works good, but:

- maybe the cache was applied.
- **only the first request** after `composer webserver` is loaded, **any other** still waiting and trying to load, waiting and trying to load, **waiting to timeout and nothing is loaded**...
- each time `composer webserver` is restarted, any **one request only is loaded - this is very strange behavior**
- no access is logged in console as in case with `[..] -t www` only => apitte-no_index_php-access vs. 
apitte-www_index_php-access_not_shown

(Windows 10 + PHP7.2 x86)

So my solution of PR was only one right solution for this problem it seems.

Sorry for not good enough of testing last time :-/

PS: But i rollbacked my master branch on my fork, so the code from PR disappeared. But I have stashed localy :)

**Comment by f3l1x** [comment]
Please type it directly in terminal, we keep the `composer webserver` just as it is.

**Comment by Vlczech** [comment]
@f3l1x: Which command did you mean to type directly? `composer webserver` i already typed directly. Or did you mean `php -S 0.0.0.0:8000 -t www`?

**Pull request closed without merging**
